x = TempEst
#average
mean(x$J)
mean(x$F)
mean(x$Mar)
mean(x$Apr)
mean(x$May)
mean(x$Jun)
mean(x$Jul)
mean(x$Aug, na.rm = TRUE)
mean(x$Sept, na.rm = TRUE)
mean(x$Oct, na.rm = TRUE)
mean(x$Nov, na.rm = TRUE)
mean(x$Dec)
#median
median(x$J)
median(x$F)
median(x$Mar)
median(x$Apr)
median(x$May)
median(x$Jun)
median(x$Jul)
median(x$Aug, na.rm = TRUE)
median(x$Sept, na.rm = TRUE)
median(x$Oct, na.rm = TRUE)
median(x$Nov, na.rm = TRUE)
median(x$Dec)
#shapiro test
shapiro.test(x$J)
shapiro.test(x$F)
shapiro.test(x$Mar)
shapiro.test(x$Apr)
shapiro.test(x$May)
shapiro.test(x$Jun)
shapiro.test(x$Jul)
shapiro.test(x$Aug)
shapiro.test(x$Sept)
shapiro.test(x$Oct)
shapiro.test(x$Nov)
shapiro.test(x$Dec)

